name: d20
version: 0.3.1+1
description: >
  D20 is a Dart library for RPG dice rolling. Supports standard notation (like "2d12", "d6+5" and "2d20-L").
homepage: https://github.com/comigor/d20

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  math_expressions: ^2.1.0-nullsafety.0

dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.11.0
